name: namaz
on:
  workflow_dispatch:
  schedule:
    - cron: "44 * * * *"
concurrency:
  group: ci-${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  halal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        run: bash -c "$(curl -Lfs https://astral.sh/uv/install.sh)"

      - name: Run python
        run: uv run ./main_test.py
        env:
          BOT_TOKEN: ${{ secrets.TOKEN }}
          SYNC_BOT: "1"
