name: namaz
on:
  schedule:
    - cron: '29 23,04,09,14,19 * * *'

concurrency:
  group: ci-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install uv
        run: bash -c "$(curl -Lf https://astral.sh/uv/install.sh)"

      - name: Run python
        run: uv run ./main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          SYNC_BOT: '0'
